### ISSUE TITLE
Cannot build current code

### ISSUE THREAD

**Issue by cggibm** [vizabi/ng2-vizabi#11]
So I downloaded the latest code. Did no change and run "npm -i" then "npm run build" and I keep hitting this error:

> ng2-vizabi-base@1.0.0 cp-linechart-src C:\_DEVCODE\tmp\ng2-vizabi
> cp -r ./node_modules/vizabi-linechart/build/dist/* ./demo/src

> ng2-vizabi-base@1.0.0 cp-mountainchart-src C:\_DEVCODE\tmp\ng2-vizabi
> cp -r ./node_modules/vizabi-mountainchart/build/dist/* ./demo/src

C:\_DEVCODE\tmp\ng2-vizabi\node_modules\npm-submodules\utils\merge-package-json.js:10
    const { base, module, localDependencies } = data;
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\_DEVCODE\tmp\ng2-vizabi\node_modules\npm-submodules\tasks\npm\build-pkg-json.task.js:4:30)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng2-vizabi-base@1.0.0 build: `cp -r ./node_modules/vizabi/build/dist/* ./demo/src && npm run cp-barrankchart-src && npm run cp-bubblechart-src && npm
run cp-bubblemap-src && npm run cp-linechart-src && npm run cp-mountainchart-src && cp ./node_modules/vizabi-ddfcsv-reader/dist/vizabi-ddfcsv-reader.js ./demo/
src && cp ./fix/webpack-build-common.js ./node_modules/@angular/cli/models && ngm build -p src --clean && npm run link`
npm ERR! Exit status 1

Any idea why? Thanks!!!

**Comment by buchslava** [comment]
@cggibm what is your current nodejs/ npm version?

**Comment by cggibm** [comment]
>npm -v
4.5.0

>node -v
v4.2.1

Using Windows 64

**Comment by angiehjort** [comment]
@cggibm i would blame the old node
i was able to build and run the project on this environment:

Windows 10 x64
Installed latest stable node and [git](https://git-scm.com/)

`npm -v` 3.10.10
`node -v` v6.10.2
`git --version` 2.12.2.windows.2

open git bash (not windows native command prompt because it has no `cp` command)
npm i
npm run build
npm start

![image](https://cloud.githubusercontent.com/assets/3648190/25162950/91841b32-2494-11e7-97d6-b1d65e4e8b83.png)

i will add node requirement to the readme (upd: [done](https://github.com/vizabi/ng2-vizabi/blob/master/README.md#troubleshooting))

besides, why do you need this ng2-vizabi repo, @cggibm?
it only used with Angular2 pages and apps
if you are not bound to use Angular2 it's better to use either [vanilla vizabi](https://github.com/vizabi/vizabi) or a [preview page](http://static.gapminderdev.org/preview/master/bubblechart.html)

tell us your use case :)

**Comment by buchslava** [comment]
@angieskazka you are right

**Comment by cggibm** [comment]
@angieskazka I am using angular2.

Actually initially I just did npm install ng2-vizabi but I always hit a problem in code where it says "Vizabi is not defined"

When you try to debug, it goes to this line on the ngOnInit:
```
    VizabiDirective.prototype.ngOnInit = function () {
        var _this = this;
        try {
            this.minInitialModel = Vizabi.utils.deepClone(this.model); // << error is here
            this.stopUrlRedirect = this.stopUrlRedirect || false;
```

So I went to try your code and saw that there is a global.d.ts file where Vizabi is declared.
Then I decided to try building your code, but it was also failing.

I was just trying out if I can use it for visualization. (I've been using highcharts most of the time).
Anyway I'll try to change my npm version and try again
Thanks!
